services:
  server:
    restart: unless-stopped
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - .git:/app/.git
